spring:
  application:
    name: swm-backend

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    out-of-order: true
springdoc:
  use-fqn: true

logging:
  level:
    org.openqa.selenium.devtools.CdpVersionFinder: ERROR

study:
  page:
    size: 20
